var newsList = [{
    "title": "Lorem ipsum dolor sit",
    "tags": ["Cundinamarca", "Covid-19", "Secondary"],
    "body": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. <br><br> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "author":"Albert Einstein <br> 24/05/2020 <br> Para Agencia Nacional de Seguridad Vial", 
    "date": "24/05/2020",
    "image": "/themes/contrib/bootstrap_sass/images/image-latest-new.png",
    "audio": "./media/audio/lorem.mp3",
    "type": "new",
    "imageIdentif": "type-person",
    "captionDescription": "Terminal de Camiones, Mayo 29 del 2020",
    "captionAutor": "Isaac Newton para ANSV",
  },
  {
    "title": "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    "tags": ["Bogotá", "Noticia", "actualidad"],
    "body": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. <br><br> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "author":"Albert Einstein <br> 22/05/2020 <br> Para Agencia Nacional de Seguridad Vial", 
    "date": "22/05/2020",
    "image": "/themes/contrib/bootstrap_sass/images/image-latest-new.png",
    "audio": "./media/audio/lorem.mp3",
    "type": "new",
    "imageIdentif": "type-bike",
    "captionDescription": "Terminal de Camiones, Mayo 29 del 2020",
    "captionAutor": "Isaac Newton para ANSV",
  },
  {
    "title": "Lorem ipsum dolor sit",
    "tags": ["Bogotá", "Noticia", "actualidad"],
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br><br>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. <br><br> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "author":"Albert Einstein <br> 18/05/2020 <br> Para Agencia Nacional de Seguridad Vial", 
    "date": "18/05/2020",
    "image": "/themes/contrib/bootstrap_sass/images/image-latest-new.png",
    "audio": "./media/audio/lorem.mp3",
    "type": "new",
    "imageIdentif": "type-bus",
    "captionDescription": "Terminal de Camiones, Mayo 29 del 2020",
    "captionAutor": "Isaac Newton para ANSV",
  },
  {
    "title": "consectetur adipiscing elit",
    "tags": ["mantenimiento", "actualidad"],
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br><br>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. <br><br> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "author":"Albert Einstein <br> 15/05/2020 <br> Para Agencia Nacional de Seguridad Vial", 
    "date": "15/05/2020",
    "image": "/themes/contrib/bootstrap_sass/images/image-latest-new.png",
    "audio": "./media/audio/lorem.mp3",
    "type": "event",
    "imageIdentif": "type-car",
    "captionDescription": "Terminal de Camiones, Mayo 29 del 2020",
    "captionAutor": "Isaac Newton para ANSV",
  },
  {
    "title": "consectetur adipiscing elit",
    "tags": ["actualidad", "capacitación"],
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br><br>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. <br><br> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "author":"Albert Einstein <br> 15/05/2020 <br> Para Agencia Nacional de Seguridad Vial", 
    "date": "15/05/2020",
    "image": "/themes/contrib/bootstrap_sass/images/image-latest-new.png",
    "audio": "./media/audio/lorem.mp3",
    "type": "event",
    "imageIdentif": "type-bike",
    "captionDescription": "Terminal de Camiones, Mayo 29 del 2020",
    "captionAutor": "Isaac Newton para ANSV",
  },
  {
    "title": "consectetur adipiscing elit",
    "tags": ["capacitación"],
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br><br><br><br>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. <br><br> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    "author":"Albert Einstein <br> 14/05/2020 <br> Para Agencia Nacional de Seguridad Vial", 
    "date": "14/05/2020",
    "image": "/themes/contrib/bootstrap_sass/images/image-latest-new.png",
    "audio": "./media/audio/lorem.mp3",
    "type": "event",
    "imageIdentif": "type-car",
    "captionDescription": "Terminal de Camiones, Mayo 29 del 2020",
    "captionAutor": "Isaac Newton para ANSV",
  },
  {
    "title": "consectetur adipiscing elit",
    "tags": ["actualidad", "capacitación"],
    "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "author":"Albert Einstein <br> 12/05/2020 <br> Para Agencia Nacional de Seguridad Vial", 
    "date": "12/05/2020",
    "image": "/themes/contrib/bootstrap_sass/images/image-latest-new.png",
    "audio": "./media/audio/lorem.mp3",
    "type": "event",
    "imageIdentif": "type-person",
    "captionDescription": "Terminal de Camiones, Mayo 29 del 2020",
    "captionAutor": "Isaac Newton para ANSV",
  }];
  