<?php 
/** 
* Implements hook_theme(). 
*/ 
function hello_world_theme() {
     
     return [
      'my_template' => [
        'template' => 'my_template',
        'variables' => ['test_var' => NULL,
                        'name' => NULL,
                        'title' => NULL,
                        'url' => NULL,
                        'nombre' => NULL
                        
                      ],
      ],

      'bye' => [
        'template' => 'bye',
        'variables' => ['test_var' => NULL,
                        'name' => NULL,
                        'my_block' => NULL,
                        'view' => NULL,
                        'slide1' => NULL,
                        'title1' => NULL,
                        'body1' => NULL,
                        'url1' => NULL,
                        'link1' => NULL,
                        'title2' => NULL,
                        'body2' => NULL,
                        'url2' => NULL,
                        'link2' => NULL,
                        'title3' => NULL,
                        'body3' => NULL,
                        'url3' => NULL,
                        'link3' => NULL,
                        'title4' => NULL,
                        'body4' => NULL,
                        'url4' => NULL,
                        'link4' => NULL,
                        'title5' => NULL,
                        'body5' => NULL,
                        'url5' => NULL,
                        'link5' => NULL,
                        'arr' => NULL
                      ],
      ],

    ];
 
}